version: '2'

services:
  db_server:
    image: ${DB}
    container_name: phpmyadmin_testing_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    volumes:
      - ./testing/testing.cnf:/etc/mysql/conf.d/testing.cnf:ro

  phpmyadmin:
    build:
      context: testing/
    container_name: phpmyadmin_testing
    volumes:
      - /sessions
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=test123
    depends_on:
      - db_server
